---
title: "Word Cloud and Cogs"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Ref : Code chunks taken from tidytext class excercises

```{r}
if (!require(tidytext)) {install.packages("tidytext")}
if (!require(tibble)) {install.packages("tibble")}
if (!require(tidyverse)) {install.packages("tidyverse")}
if (!require(wordcloud)) {install.packages("wordcloud")}
if (!require(ggplot2)) {install.packages("ggplot2")}
if (!require(igraph)) {install.packages("igraph")}
```

Read swiggy and zomato files

```{r cars}
swiggy <- readLines('data/swiggy.txt')
zomato <- readLines('data/zomato.txt')
```

Build document term matrix

```{r build dtm}
build_dtm <- function(corpus) {
  df = data_frame(text = corpus)  #create dataframe
  df_tokens = df %>% 
    mutate(doc = row_number()) %>% 
    unnest_tokens(word, text) %>% 
    anti_join(stop_words) %>% 
    group_by(doc) %>% 
    count(word, sort=TRUE)
  
  df_counts = df_tokens %>% rename(value = n)
  dtm = df_counts %>% cast_sparse(doc, word, value)
 
   # order rows and colms putting max mass on the top-left corner of the DTM
  colsum = apply(dtm, 2, sum)    
  col.order = order(colsum, decreasing=TRUE)
  row.order = order(rownames(dtm) %>% as.numeric())
  dtm1 = dtm[row.order, col.order]
  return(dtm1)  
}

swiggy_dtm = build_dtm(swiggy)
zomato_dtm = build_dtm(zomato)
```

Plot Word Clouds

```{r word cloud}
build_wordcloud <- function(dtm) {
 if (ncol(dtm) > 20000) {
   chunk = round(ncol(dtm)/100)
   a = rep(chunk,99)
   b = cumsum(a)
   rm(a)
   b = c(0,b,ncol(dtm))
   
   ss.col = c(NULL)
   for (i in 1:(length(b)-1)) {
     tempdtm = dtm[,(b[i]+1):(b[i+1])]
     s = colSums(as.matrix(tempdtm))
     ss.col = c(ss.col,s)
    } # i loop ends

   tsum = ss.col
  }
  else {
    tsum = apply(dtm, 2, sum)
  }

 tsum = tsum[order(tsum, decreasing = T)]
 return (tsum)
}

tsum <- build_wordcloud(swiggy_dtm)
wordcloud(names(tsum), tsum,     # words, their freqs 
          scale = c(3.5, 0.5),     # range of word sizes
          5,                     # min.freq of words to consider
          max.words = 150,       # max #words
          colors = brewer.pal(8, "Dark2"))    # Plot results in a word cloud 
          title(sub = "Swiggy Tweets Word Cloud")     # title for the wordcloud display

```
```{r plot barchart}
plot.barchart <- function(dtm) {
  a0 = apply(dtm, 2, sum)
  a1 = order(a0, decreasing = TRUE)
  tsum = a0[a1]
  return (tsum)
}
 # plot barchart for top tokens
 
  

tsum <- plot.barchart(swiggy_dtm)
test = as.data.frame(round(tsum[1:15],0))  #max words to plot
p = ggplot(test, aes(x = rownames(test), y = test[,])) + 
       geom_bar(stat = "identity", fill = "Brown") +
       geom_text(aes(label = test[,]), vjust= -0.20) + 
       theme(axis.text.x = element_text(angle = 90, hjust = 1))

 plot(p)
 
 tsum <- plot.barchart(zomato_dtm)
test = as.data.frame(round(tsum[1:15],0))  #max words to plot
p = ggplot(test, aes(x = rownames(test), y = test[,])) + 
       geom_bar(stat = "identity", fill = "Brown") +
       geom_text(aes(label = test[,]), vjust= -0.20) + 
       theme(axis.text.x = element_text(angle = 90, hjust = 1))

 plot(p)
```

```{r create cog}
max_center_nodes <- 4
max_vertices <- 5
distill.cog = function(dtm) {
 dtm_matrix = as.matrix(dtm)  #convert dtm to matrix
 adj.mat = t(dtm_matrix) %*% dtm_matrix   #Transpose the matrix
 diag(adj.mat) = 0     #remove self word references from matrix
 col_sum = order(apply(adj.mat, 2, sum), decreasing = T)  #order by sum
 sum_matrix = as.matrix(adj.mat[col_sum[1:50], col_sum[1:50]])

 a = colSums(sum_matrix) # get sum in vector
 b = order(-a) #arrange in descending order
  
 row_col_matrix = sum_matrix[b, b]  #create matrix with rows and columns
 diag(row_col_matrix) =  0
 
 word_count = NULL
 for (i in 1:max_center_nodes) {
  thresh1 = row_col_matrix[i,][order(-row_col_matrix[i, ])[max_vertices]]
  row_col_matrix[i, row_col_matrix[i,] < thresh1] = 0 
  row_col_matrix[i, row_col_matrix[i,] > 0 ] = 1
  word = names(row_col_matrix[i, row_col_matrix[i,] > 0])
  row_col_matrix[(i+1):nrow(row_col_matrix), match(word,colnames(row_col_matrix))] = 0
  word_count = c(word_count, word)
}
 row_col_matrix1 = row_col_matrix[match(word_count, colnames(row_col_matrix)), match(word_count, colnames(row_col_matrix))]
 order = colnames(row_col_matrix)[which(!is.na(match(colnames(row_col_matrix), colnames(row_col_matrix1))))]  #remove NA rows
 row_col_matrix2 = row_col_matrix1[match(order, colnames(row_col_matrix1)), match(order, colnames(row_col_matrix1))]
 return (row_col_matrix2)
}

dtm_plot <-  distill.cog(swiggy_dtm)
graph <- graph.adjacency(dtm_plot, mode = "undirected", weighted=T) #Create Network object
graph <- simplify(graph) 
V(graph)$color[1:max_center_nodes] = "green" #central node color
V(graph)$color[max_center_nodes+1:length(V(graph))] = "pink"  #vertex colors
graph = delete.vertices(graph, V(graph)[ degree(graph) == 0 ]) #delete empty vertices
plot(graph, layout = layout.kamada.kawai, main = "Swiggy COG")
  
dtm_plot <-  distill.cog(zomato_dtm)
graph <- graph.adjacency(dtm_plot, mode = "undirected", weighted=T) #Create Network object
graph <- simplify(graph) 
V(graph)$color[1:4] <- "green" #central node color
V(graph)$color[5:length(V(graph))] <- "pink"  #vertex colors
graph = delete.vertices(graph, V(graph)[ degree(graph) == 0 ]) #delete empty vertices
plot(graph, layout = layout.kamada.kawai, main = "Zomato COG")

```

